# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progresja.ui'
#
# Created: Thu Dec 29 10:43:04 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from Connections import *
from PyQt4 import Qwt5

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object, Connections):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1201, 682)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1201, 611))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(450, 0, 471, 581))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 171, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.frame_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 60, 471, 231))
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 320, 161, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.frame_2)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(0, 340, 471, 201))
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.spinBox_2 = QtGui.QSpinBox(self.frame_2)
        self.spinBox_2.setGeometry(QtCore.QRect(60, 0, 59, 27))
        self.spinBox_2.setMinimum(1900)
        self.spinBox_2.setMaximum(3000)
        self.spinBox_2.setProperty(_fromUtf8("value"), 2010)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton_2 = QtGui.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 290, 471, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 546, 471, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_9 = QtGui.QPushButton(self.frame_2)
        self.pushButton_9.setGeometry(QtCore.QRect(286, 0, 181, 51))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 451, 581))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 40, 111, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 60, 451, 291))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 380, 67, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(0, 400, 451, 181))
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(0, 350, 451, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.textEdit = QtGui.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(50, 0, 151, 31))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(210, 10, 31, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.spinBox = QtGui.QSpinBox(self.frame)
        self.spinBox.setGeometry(QtCore.QRect(250, 0, 61, 27))
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 21, 171, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(10, 290, 291, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 540, 136, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.listWidget = QtGui.QListWidget(self.tab_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 38, 221, 214))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.listWidget_2 = QtGui.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 310, 281, 231))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(146, 540, 146, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_10 = QtGui.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(110, 250, 121, 27))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(300, 286, 897, 281))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.qwtPlot = Qwt5.QwtPlot(self.tab_3)
        self.qwtPlot.setGeometry(QtCore.QRect(0, 0, 891, 256))
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_4)
        self.textEdit_2.setGeometry(QtCore.QRect(-1, 15, 604, 242))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(606, 1, 120, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(4, 0, 110, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.textEdit_3 = QtGui.QTextEdit(self.tab_4)
        self.textEdit_3.setGeometry(QtCore.QRect(604, 16, 287, 240))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.frame_4 = QtGui.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(234, 3, 557, 274))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_18 = QtGui.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(92, 69, 87, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(8, 87, 71, 19))
        self.doubleSpinBox_2.setDecimals(5)
        self.doubleSpinBox_2.setMaximum(999999999.0)
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setProperty(_fromUtf8("value"), 2.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(100, 129, 70, 18))
        self.doubleSpinBox_4.setProperty(_fromUtf8("value"), 3.8)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.label_13 = QtGui.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(9, 70, 67, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.spinBox_4 = QtGui.QSpinBox(self.frame_4)
        self.spinBox_4.setGeometry(QtCore.QRect(105, 87, 67, 18))
        self.spinBox_4.setProperty(_fromUtf8("value"), 1)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.label_16 = QtGui.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(130, 109, 31, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(9, 129, 81, 19))
        self.doubleSpinBox_3.setProperty(_fromUtf8("value"), 3.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.label_15 = QtGui.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(50, 109, 31, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox.setGeometry(QtCore.QRect(10, 23, 161, 17))
        self.doubleSpinBox.setMaximum(999999999.0)
        self.doubleSpinBox.setProperty(_fromUtf8("value"), 1.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.label_19 = QtGui.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(10, 148, 94, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.spinBox_5 = QtGui.QSpinBox(self.frame_4)
        self.spinBox_5.setGeometry(QtCore.QRect(108, 149, 56, 16))
        self.spinBox_5.setProperty(_fromUtf8("value"), 5)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.label_12 = QtGui.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(10, 3, 161, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.radioButton = QtGui.QRadioButton(self.frame_4)
        self.radioButton.setGeometry(QtCore.QRect(10, 39, 163, 16))
        self.radioButton.setAutoFillBackground(True)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.label_14 = QtGui.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(10, 109, 41, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame_4)
        self.radioButton_2.setGeometry(QtCore.QRect(9, 54, 128, 19))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.frame_5 = QtGui.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(184, 98, 208, 31))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.radioButton_5 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_5.setGeometry(QtCore.QRect(3, 12, 95, 17))
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.radioButton_6 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_6.setGeometry(QtCore.QRect(104, 12, 102, 17))
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.label_20 = QtGui.QLabel(self.frame_5)
        self.label_20.setGeometry(QtCore.QRect(56, -1, 96, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.frame_6 = QtGui.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(182, 3, 208, 94))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_21 = QtGui.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(4, 2, 99, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.radioButton_7 = QtGui.QRadioButton(self.frame_6)
        self.radioButton_7.setGeometry(QtCore.QRect(4, 15, 102, 17))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.radioButton_8 = QtGui.QRadioButton(self.frame_6)
        self.radioButton_8.setGeometry(QtCore.QRect(100, 16, 107, 17))
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.frame_8 = QtGui.QFrame(self.frame_6)
        self.frame_8.setGeometry(QtCore.QRect(2, 39, 204, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_8.setPalette(palette)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setLineWidth(2)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.label_30 = QtGui.QLabel(self.frame_8)
        self.label_30.setGeometry(QtCore.QRect(6, -1, 51, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.frame_8)
        self.label_31.setGeometry(QtCore.QRect(8, 11, 48, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.spinBox_6 = QtGui.QSpinBox(self.frame_8)
        self.spinBox_6.setGeometry(QtCore.QRect(6, 25, 48, 20))
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.label_32 = QtGui.QLabel(self.frame_8)
        self.label_32.setGeometry(QtCore.QRect(126, 0, 67, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.radioButton_10 = QtGui.QRadioButton(self.frame_8)
        self.radioButton_10.setGeometry(QtCore.QRect(117, 14, 66, 17))
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.radioButton_9 = QtGui.QRadioButton(self.frame_8)
        self.radioButton_9.setGeometry(QtCore.QRect(117, 30, 82, 17))
        self.radioButton_9.setChecked(False)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.label_33 = QtGui.QLabel(self.frame_8)
        self.label_33.setGeometry(QtCore.QRect(62, 0, 55, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.frame_8)
        self.label_34.setGeometry(QtCore.QRect(63, 13, 46, 13))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.spinBox_7 = QtGui.QSpinBox(self.frame_8)
        self.spinBox_7.setGeometry(QtCore.QRect(62, 25, 45, 19))
        self.spinBox_7.setProperty(_fromUtf8("value"), 48)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.frame_7 = QtGui.QFrame(self.frame_4)
        self.frame_7.setGeometry(QtCore.QRect(392, 1, 163, 271))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.label_24 = QtGui.QLabel(self.frame_7)
        self.label_24.setGeometry(QtCore.QRect(2, 0, 137, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.checkBox = QtGui.QCheckBox(self.frame_7)
        self.checkBox.setGeometry(QtCore.QRect(3, 14, 157, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(6, 47, 65, 16))
        self.doubleSpinBox_5.setDecimals(5)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(76, 45, 67, 16))
        self.doubleSpinBox_6.setDecimals(5)
        self.doubleSpinBox_6.setProperty(_fromUtf8("value"), 10.0)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.label_25 = QtGui.QLabel(self.frame_7)
        self.label_25.setGeometry(QtCore.QRect(12, 31, 46, 13))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.frame_7)
        self.label_26.setGeometry(QtCore.QRect(79, 29, 46, 13))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.frame_7)
        self.label_27.setGeometry(QtCore.QRect(10, 61, 46, 13))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(8, 76, 62, 16))
        self.doubleSpinBox_7.setMaximum(10.0)
        self.doubleSpinBox_7.setSingleStep(0.1)
        self.doubleSpinBox_7.setProperty(_fromUtf8("value"), 0.1)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.checkBox_3 = QtGui.QCheckBox(self.frame_7)
        self.checkBox_3.setGeometry(QtCore.QRect(4, 96, 158, 17))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.label_40 = QtGui.QLabel(self.frame_7)
        self.label_40.setGeometry(QtCore.QRect(86, 112, 46, 13))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.spinBox_18 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_18.setGeometry(QtCore.QRect(6, 131, 51, 16))
        self.spinBox_18.setMinimum(1)
        self.spinBox_18.setObjectName(_fromUtf8("spinBox_18"))
        self.label_41 = QtGui.QLabel(self.frame_7)
        self.label_41.setGeometry(QtCore.QRect(12, 115, 46, 13))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.spinBox_19 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_19.setGeometry(QtCore.QRect(85, 130, 51, 16))
        self.spinBox_19.setProperty(_fromUtf8("value"), 8)
        self.spinBox_19.setObjectName(_fromUtf8("spinBox_19"))
        self.frame_9 = QtGui.QFrame(self.frame_4)
        self.frame_9.setGeometry(QtCore.QRect(2, 175, 181, 61))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.label_35 = QtGui.QLabel(self.frame_9)
        self.label_35.setGeometry(QtCore.QRect(2, 1, 171, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.checkBox_2 = QtGui.QCheckBox(self.frame_9)
        self.checkBox_2.setGeometry(QtCore.QRect(1, 17, 177, 20))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.label_36 = QtGui.QLabel(self.frame_9)
        self.label_36.setGeometry(QtCore.QRect(89, 35, 91, 20))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.spinBox_8 = QtGui.QSpinBox(self.frame_9)
        self.spinBox_8.setGeometry(QtCore.QRect(27, 35, 52, 22))
        self.spinBox_8.setSingleStep(0)
        self.spinBox_8.setProperty(_fromUtf8("value"), 3)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.label_37 = QtGui.QLabel(self.frame_9)
        self.label_37.setGeometry(QtCore.QRect(7, 37, 23, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(303, 568, 57, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_17.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_28 = QtGui.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(371, 569, 60, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_28.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(436, 570, 46, 13))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_29.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.frame_11 = QtGui.QFrame(self.tab_2)
        self.frame_11.setGeometry(QtCore.QRect(8, 1, 224, 26))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.spinBox_3 = QtGui.QSpinBox(self.frame_11)
        self.spinBox_3.setGeometry(QtCore.QRect(163, 1, 59, 20))
        self.spinBox_3.setMinimum(1900)
        self.spinBox_3.setMaximum(3000)
        self.spinBox_3.setProperty(_fromUtf8("value"), 2010)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.label_8 = QtGui.QLabel(self.frame_11)
        self.label_8.setGeometry(QtCore.QRect(2, 4, 94, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.spinBox_9 = QtGui.QSpinBox(self.frame_11)
        self.spinBox_9.setGeometry(QtCore.QRect(96, 1, 47, 22))
        self.spinBox_9.setMaximum(3000)
        self.spinBox_9.setProperty(_fromUtf8("value"), 2003)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.label_39 = QtGui.QLabel(self.frame_11)
        self.label_39.setGeometry(QtCore.QRect(146, 4, 19, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.pushButton_11 = QtGui.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 562, 282, 23))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.frame_12 = QtGui.QFrame(self.tab_2)
        self.frame_12.setGeometry(QtCore.QRect(929, -1, 268, 249))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.listWidget_3 = QtGui.QListWidget(self.frame_12)
        self.listWidget_3.setGeometry(QtCore.QRect(1, 20, 265, 202))
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.pushButton_8 = QtGui.QPushButton(self.frame_12)
        self.pushButton_8.setGeometry(QtCore.QRect(165, 222, 102, 27))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_7 = QtGui.QPushButton(self.frame_12)
        self.pushButton_7.setGeometry(QtCore.QRect(82, 222, 83, 27))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_5 = QtGui.QPushButton(self.frame_12)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 222, 83, 27))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.label_11 = QtGui.QLabel(self.frame_12)
        self.label_11.setGeometry(QtCore.QRect(2, 0, 67, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.frame_10 = QtGui.QFrame(self.tab_2)
        self.frame_10.setGeometry(QtCore.QRect(928, 249, 180, 30))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.radioButton_11 = QtGui.QRadioButton(self.frame_10)
        self.radioButton_11.setGeometry(QtCore.QRect(1, 12, 82, 17))
        self.radioButton_11.setChecked(True)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.radioButton_12 = QtGui.QRadioButton(self.frame_10)
        self.radioButton_12.setGeometry(QtCore.QRect(68, 12, 114, 17))
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.label_38 = QtGui.QLabel(self.frame_10)
        self.label_38.setGeometry(QtCore.QRect(8, -2, 65, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.frame_3 = QtGui.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(927, 279, 208, 20))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.radioButton_3 = QtGui.QRadioButton(self.frame_3)
        self.radioButton_3.setGeometry(QtCore.QRect(1, 1, 110, 20))
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.frame_3)
        self.radioButton_4.setGeometry(QtCore.QRect(107, 1, 102, 20))
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1201, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuExit = QtGui.QMenu(self.menubar)
        self.menuExit.setObjectName(_fromUtf8("menuExit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionNowy_sezon = QtGui.QAction(MainWindow)
        self.actionNowy_sezon.setObjectName(_fromUtf8("actionNowy_sezon"))
        self.menuExit.addAction(self.actionNowy_sezon)
        self.menuExit.addAction(self.actionExit)
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.connect()

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Tu wklej wyniki z sezonu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Ciągi do dalszej analizy:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Sezon", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Generuj ciągi", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Zapisz do pliku", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MainWindow", "Czyść wszystko", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Tu wklej tabele", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Zespoły:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Wyłuskaj zespoły z tabeli", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Kraj", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Liga", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Przygotowywanie danych", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Lista dostępnych  lig", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Lista zespołów w wybranym sezonie i lidze", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Dodaj do portfela", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Dodaj wszystkie", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MainWindow", "Dodaj wszystkie", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Cash flow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Parametry statystyczne", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Parametry finansowe", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Parametry finansowe i statystyczne", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Długość elemnt.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Mnożnik", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Do:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Od: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Granica progresji", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Stawka początkowa", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Ciąg Fibonacciego", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Kurs", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Progresja iloczynowa", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("MainWindow", "Odrzuć zespół", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("MainWindow", "Zresetuj stawkę", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Granica progresji", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Rozpoczęcie gry", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_7.setText(QtGui.QApplication.translate("MainWindow", "Zacznij od razu", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_8.setText(QtGui.QApplication.translate("MainWindow", "Zacznij po remisie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Zacznij od", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "kolejki nr.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Ze stawkami", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_10.setText(QtGui.QApplication.translate("MainWindow", "Nowymi", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_9.setText(QtGui.QApplication.translate("MainWindow", "Wyliczonymi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Skończ na", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "kolejce nr.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Funkcje badania wydajności", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Licz dla zakresu mnożników", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Od:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Do:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Co:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "Licz dla zakresu granic prog.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Do:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Od:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Zabezp. przed zerwaniem progresji", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Stop do pojawienia się sukcesu:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "niepowodzeniach", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "po", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Cash Flow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Wolumen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Suma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Wybierz sezony od", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "do", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("MainWindow", "Dodaj wszystkie sezony zaznaczonej drużyny", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "Przelicz jeszcze raz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Usuń wszystkie", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Usuń", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Portfel", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_11.setText(QtGui.QApplication.translate("MainWindow", "Na remisy", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_12.setText(QtGui.QApplication.translate("MainWindow", "Przeciwko remisom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Sposób gry", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "Remisy do połowy", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("MainWindow", "Remisy na koniec", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Analiza danych", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExit.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNowy_sezon.setText(QtGui.QApplication.translate("MainWindow", "Nowy sezon", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

